### ISSUE TITLE
Include .DS_Store files in the .gitignore file of the files generated by rsgem

### ISSUE THREAD

**Issue by mrubi-rootstrap** [rootstrap/rsgem#54]
**Is your feature request related to a problem? Please describe.**

`.DS_Store` files are not ignored by git

**Describe the solution you'd like**

Add the line

```
.DS_Store
```

 to the `.gitignore` file in the project generated by `rsgem`

**Comment by juanmanuelramallo** [comment]
Given this is a file exclusive to macOS (system dependent) I'd rather nudge macOS users to add `.DS_Store` to their global `~/.gitignore` file, don't you think?

**Comment by mrubi-rootstrap** [comment]
Yes, it makes sense but there's a catch.
I usually use `/bin/bash` a Docker container for some development tasks.
The Docker container usually has a git client of its own.
I try not to use git from the Docker container but sometimes I inadvertently do it.
Using a git config local to the project works out of the box for me even in those cases

**Comment by juanmanuelramallo** [comment]
I guess it'd be better for the dockerfile to include the default .gitignore for the user. Otherwise we would be adding some OS-specific noise to rsgem IMHO. Closing it for now.
