### ISSUE TITLE
Update Bundler gem version for Github Actions

### ISSUE THREAD

**Issue by JulianPasquale** [rootstrap/rsgem#63]
When using flag `--ci=github_actions`, the generated file `.github/workflows/ci.yml` [uses bundler:1.17.3](https://github.com/rootstrap/rsgem/blob/master/.github/workflows/ci.yml#L32).

In [Bundler 2](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html), they removed support for Ruby < 2.3. And `ruby-versions` matrix for Github Actions starts from Ruby 2.5, so maybe this could be a nice update for new gems generated.

**Comment by horacio** [comment]
Sounds good! Yeah, 2.3 and 2.4 are both EOLed. I can try to tackle this.
